-- ============================

-- This file was created using Derby's dblook utility.
-- Timestamp: 2024-10-15 11:32:16.818
-- Source database is: D:/RealDB
-- Connection URL is: jdbc:derby:D:/RealDB
-- Specified schema is: APP
-- appendLogs: false

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE "APP"."ACQUITTANCENUMBER_LPS" ("NUMBER" VARCHAR(20));

CREATE TABLE "APP"."SERVICETABLE4" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(30), "TYPE" VARCHAR(30), "CATEGORY" VARCHAR(30), "WHEIGHT" VARCHAR(30), "SERIAL" VARCHAR(30), "BARCOD" VARCHAR(30), "DATE" VARCHAR(30));

CREATE TABLE "APP"."INVOICEPARENTDB4" ("ID" VARCHAR(20) NOT NULL, "PAYMENT" VARCHAR(20), "DISCOUNT" VARCHAR(10), "VALUE" VARCHAR(10), "CLIENT" VARCHAR(100), "SALLER" VARCHAR(100), "DATE" VARCHAR(20));

CREATE TABLE "APP"."INVOICECHILDDB" ("ID" VARCHAR(20) NOT NULL, "MAKE" VARCHAR(200), "MED" VARCHAR(20), "PRICE" VARCHAR(20), "VALUE" VARCHAR(20));

CREATE TABLE "APP"."ARTIKULSDB_LPS" ("ARTIKUL" VARCHAR(100), "QUANTITY" INTEGER, "MED" VARCHAR(20), "VALUE" VARCHAR(20));

CREATE TABLE "APP"."BASE3" ("CLIENT" VARCHAR(50), "BRAND" VARCHAR(50), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "SERIAL" VARCHAR(20), "BARCOD" VARCHAR(20), "DOING" VARCHAR(20), "READY" VARCHAR(20), "DATE" VARCHAR(20));

CREATE TABLE "APP"."SCRAB3" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(40), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "SERIAL" VARCHAR(20), "BARCOD" VARCHAR(20), "SCRABDATE" VARCHAR(20), "REASONS" VARCHAR(1000), "DOING" VARCHAR(50));

CREATE TABLE "APP"."SO" ("CLIENT" VARCHAR(50), "BRAND" VARCHAR(50), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "DOING" VARCHAR(20), "READY" VARCHAR(20), "DATE" VARCHAR(20));

CREATE TABLE "APP"."MAINTABLE2" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(40), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "SERIAL" VARCHAR(20), "BARCOD" VARCHAR(20), "DOING" VARCHAR(20), "SERVICEDATE" VARCHAR(20), "DATEDOING" VARCHAR(20), "PARTS" VARCHAR(1000));

CREATE TABLE "APP"."SERVICE2" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(30), "TYPE" VARCHAR(30), "CATEGORY" VARCHAR(30), "WHEIGHT" VARCHAR(30), "SERIAL" VARCHAR(30), "BARCOD" VARCHAR(30), "SERVICEDATE" VARCHAR(30));

CREATE TABLE "APP"."SERVICE3" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(30), "TYPE" VARCHAR(30), "CATEGORY" VARCHAR(30), "WHEIGHT" VARCHAR(30), "SERIAL" VARCHAR(30), "BARCOD" VARCHAR(30), "SERVICEDATE" VARCHAR(30), "DOING" VARCHAR(50));

CREATE TABLE "APP"."FIRMTABLE2" ("FIRM" VARCHAR(100), "CITY" VARCHAR(50), "ADDRESS" VARCHAR(100), "EIK" VARCHAR(50), "MOL" VARCHAR(50), "EMAIL" VARCHAR(30), "PERSON" VARCHAR(50), "TELPERSON" VARCHAR(30), "BANK" VARCHAR(30), "BIC" VARCHAR(30), "IBAN" VARCHAR(30), "DISCOUNT" VARCHAR(10));

CREATE TABLE "APP"."INVOICENUMBER_LPS" ("INVOICE_NUMBER" VARCHAR(20));

CREATE TABLE "APP"."SO_TABLE" ("SO" VARCHAR(20));

CREATE TABLE "APP"."COMPOSITE" ("INVOICE" VARCHAR(20) NOT NULL, "PROTOKOL" VARCHAR(20) NOT NULL, "INFO" VARCHAR(20));

CREATE TABLE "APP"."PERSONSTABLE" ("NAME" VARCHAR(50) NOT NULL, "TEL" VARCHAR(20), "DISCOUNT" VARCHAR(10), "INCORRECTPERSON" VARCHAR(2));

CREATE TABLE "APP"."BRACKNUMBER" ("BR_NUMBER" VARCHAR(20));

CREATE TABLE "APP"."INVOICECHILDDB3" ("ID" VARCHAR(20) NOT NULL, "MAKE" VARCHAR(200), "MED" VARCHAR(20), "QUANTITY" VARCHAR(50), "PRICE" VARCHAR(20), "VALUE" VARCHAR(20));

CREATE TABLE "APP"."INVOICENUMBER" ("INVOICE_NUMBER" VARCHAR(20));

CREATE TABLE "APP"."MAIN3" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(40), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "SERIAL" VARCHAR(20), "BARCOD" VARCHAR(20), "SERVICEDATE" VARCHAR(20), "DATEDOING" VARCHAR(20), "PARTS" VARCHAR(1000), "DOING" VARCHAR(50));

CREATE TABLE "APP"."SERVICETABLE2" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(30), "TYPE" VARCHAR(30), "CATEGORY" VARCHAR(30), "WHEIGHT" VARCHAR(30), "SERIAL" VARCHAR(30), "BARCOD" VARCHAR(30), "DATE" VARCHAR(30));

CREATE TABLE "APP"."FIRM2" ("FIRM" VARCHAR(30), "CITY" VARCHAR(20), "ADDRESS" VARCHAR(100), "EIK" VARCHAR(20), "MOL" VARCHAR(20), "TELFIRM" VARCHAR(20), "EMAIL" VARCHAR(20), "PERSON" VARCHAR(20), "TELPERSON" VARCHAR(20), "BANK" VARCHAR(20), "BIC" VARCHAR(20), "IBAN" VARCHAR(20));

CREATE TABLE "APP"."PROFORMCHILDDB" ("ID" VARCHAR(20), "MAKE" VARCHAR(200), "MED" VARCHAR(20), "QUANTITY" VARCHAR(50), "PRICE" VARCHAR(20), "VALUE" VARCHAR(20));

CREATE TABLE "APP"."PROFORMCHILDDB2" ("ID" VARCHAR(20), "MAKE" VARCHAR(500), "MED" VARCHAR(20), "QUANTITY" VARCHAR(50), "PRICE" VARCHAR(20), "VALUE" VARCHAR(20), "CLIENT" VARCHAR(100), "KONTRAGENT" VARCHAR(50), "INVOICEBYKONTRAGENT" VARCHAR(50));

CREATE TABLE "APP"."SCRAB" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(40), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "SERIAL" VARCHAR(20), "BARCOD" VARCHAR(20), "SCRABDATE" VARCHAR(20), "REASONS" VARCHAR(1000));

CREATE TABLE "APP"."INVOICECHILDDB2" ("ID" VARCHAR(20) NOT NULL, "MAKE" VARCHAR(200), "MED" VARCHAR(20), "QUANTITY" VARCHAR(50), "PRICE" VARCHAR(20), "VALUE" VARCHAR(20));

CREATE TABLE "APP"."NEWEXTINGUISHERSDB" ("TYPE" VARCHAR(50), "WHEIGHT" VARCHAR(50), "CATEGORY" VARCHAR(20), "BRAND" VARCHAR(50), "QUANTITIY" VARCHAR(10), "PRICE" VARCHAR(20));

CREATE TABLE "APP"."INVOICEPARENTDB2" ("ID" VARCHAR(20) NOT NULL, "PAYMENT" VARCHAR(20), "DISCOUNT" VARCHAR(10), "VALUE" VARCHAR(10), "CLIENT" VARCHAR(100), "SALLER" VARCHAR(100), "DATE" VARCHAR(20));

CREATE TABLE "APP"."ACQUITTANCECHILDDB" ("ID" VARCHAR(20), "ARTIKUL" VARCHAR(200), "MED" VARCHAR(20), "QUANTITY" VARCHAR(50), "PRICE" VARCHAR(20), "VALUE" VARCHAR(20), "CLIENT" VARCHAR(100));

CREATE TABLE "APP"."EXTINGUISHINGAGENTTABLE" ("AGENT" VARCHAR(50), "BRAND" VARCHAR(50), "BATCH" VARCHAR(50), "FIT" VARCHAR(30));

CREATE TABLE "APP"."ARTIKULSDB" ("ARTIKUL" VARCHAR(500), "QUANTITY" INTEGER, "MED" VARCHAR(20), "VALUE" VARCHAR(20), "INVOICE" VARCHAR(10), "CLIENT" VARCHAR(50), "DATE" VARCHAR(10), "OPERATOR" VARCHAR(50), "PERCENTPROFIT" VARCHAR(50), "BARCODE" VARCHAR(20));

CREATE TABLE "APP"."PROTOKOLTABLEDB2" ("CLIENT" VARCHAR(50), "TYPE" VARCHAR(20), "WHEIGHT" VARCHAR(30), "BARCOD" VARCHAR(20), "SERIAL" VARCHAR(30), "CATEGORY" VARCHAR(10), "BRAND" VARCHAR(30), "T_O" VARCHAR(20), "P" VARCHAR(20), "HI" VARCHAR(20), "PARTS" VARCHAR(1000), "DOUBLE_WRITTEN" VARCHAR(10), "NUMBER" VARCHAR(20), "PERSON" VARCHAR(50), "DATE" VARCHAR(20));

CREATE TABLE "APP"."PROTOKOL" ("CLIENT" VARCHAR(40), "TYPE" VARCHAR(20), "WHEIGHT" VARCHAR(20), "CATEGORY" VARCHAR(20), "BRAND" VARCHAR(40), "SERIAL" VARCHAR(20), "BARCOD" VARCHAR(20), "DOING" VARCHAR(50), "PARTS" VARCHAR(1000), "PROTOKOLNUMBER" VARCHAR(20), "PROTOKOLDATE" VARCHAR(20));

CREATE TABLE "APP"."PARTSQUANTITYDB" ("PART" VARCHAR(200), "QUANTITY" INTEGER);

CREATE TABLE "APP"."TEST" ("ID" VARCHAR(20), "NAME" VARCHAR(100));

CREATE TABLE "APP"."SERVICEDB" ("ARTIKUL" VARCHAR(300), "QUANTITY" INTEGER, "MED" VARCHAR(20), "VALUE" VARCHAR(20), "INVOICE" VARCHAR(20), "CLIENT" VARCHAR(50), "DATE" VARCHAR(20), "OPERATOR" VARCHAR(30), "PERCENTPROFIT" VARCHAR(5));

CREATE TABLE "APP"."PARTSQUANTITYDB_LPS" ("PART" VARCHAR(200), "QUANTITY" INTEGER);

CREATE TABLE "APP"."PRICETABLE" ("PART" VARCHAR(50), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "PRICE" VARCHAR(20));

CREATE TABLE "APP"."PR_NUMBER" ("PR_NUMBER" VARCHAR(20));

CREATE TABLE "APP"."WORKPRICEDB" ("DO" VARCHAR(50), "PRICE" DOUBLE);

CREATE TABLE "APP"."ARTIKULS" ("ARTIKUL" VARCHAR(100), "QUANTITY" VARCHAR(20), "MED" VARCHAR(20), "VALUE" VARCHAR(20));

CREATE TABLE "APP"."FIRMTABLE" ("FIRM" VARCHAR(30), "CITY" VARCHAR(20), "ADDRESS" VARCHAR(100), "EIK" VARCHAR(20), "MOL" VARCHAR(20), "TELFIRM" VARCHAR(20), "EMAIL" VARCHAR(20), "PERSON" VARCHAR(20), "TELPERSON" VARCHAR(20), "BANK" VARCHAR(20), "BIC" VARCHAR(20), "IBAN" VARCHAR(20), "DISCOUNT" VARCHAR(10));

CREATE TABLE "APP"."FRIENDS" ("ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(20));

CREATE TABLE "APP"."BRACKTABLEDB" ("CLIENT" VARCHAR(50), "TYPE" VARCHAR(20), "WHEIGHT" VARCHAR(30), "BARCOD" VARCHAR(20), "SERIAL" VARCHAR(30), "CATEGORY" VARCHAR(20), "BRAND" VARCHAR(20), "REASONS" VARCHAR(200), "NUMBER" VARCHAR(20), "TEHNIK" VARCHAR(50), "DATE" VARCHAR(20));

CREATE TABLE "APP"."SERVICETABLE5" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(30), "TYPE" VARCHAR(30), "CATEGORY" VARCHAR(30), "WHEIGHT" VARCHAR(30), "SERIAL" VARCHAR(30), "BARCOD" VARCHAR(30), "����" VARCHAR(30));

CREATE TABLE "APP"."PROTOKOLTABLEDB3" ("CLIENT" VARCHAR(100), "TYPE" VARCHAR(30), "WHEIGHT" VARCHAR(30), "BARCOD" VARCHAR(30), "SERIAL" VARCHAR(30), "CATEGORY" VARCHAR(20), "BRAND" VARCHAR(50), "T_O" VARCHAR(20), "P" VARCHAR(20), "HI" VARCHAR(20), "PARTS" VARCHAR(1000), "VALUE" DOUBLE, "DOUBLE_WRITTEN" VARCHAR(10), "NUMBER" VARCHAR(20), "PERSON" VARCHAR(100), "DATE" VARCHAR(20));

CREATE TABLE "APP"."INVOICECHILDDB5" ("ID" VARCHAR(20), "MAKE" VARCHAR(200), "MED" VARCHAR(20), "QUANTITY" VARCHAR(50), "PRICE" VARCHAR(20), "VALUE" VARCHAR(20));

CREATE TABLE "APP"."PARTSTABLEDB2" ("PART" VARCHAR(100), "TYPE" VARCHAR(20), "WHEIGHT" VARCHAR(20), "CATEGORY" VARCHAR(20), "QUANTITY" DOUBLE, "PRICE" DOUBLE);

CREATE TABLE "APP"."BASE2" ("CLIENT" VARCHAR(50), "BRAND" VARCHAR(50), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "SERIAL" VARCHAR(20), "BARCOD" VARCHAR(20), "WHEIGHT" VARCHAR(20), "DOING" VARCHAR(20), "READY" VARCHAR(20), "DATE" VARCHAR(20));

CREATE TABLE "APP"."PROTOKOLBRACK" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(40), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "SERIAL" VARCHAR(20), "BARCOD" VARCHAR(20), "SCRABDATE" VARCHAR(20), "REASONS" VARCHAR(1000), "BR_NUMBER" VARCHAR(20));

CREATE TABLE "APP"."SCRABTABLE2" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(40), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "SERIAL" VARCHAR(20), "BARCOD" VARCHAR(20), "REASONS" VARCHAR(1000));

CREATE TABLE "APP"."DELIVERYARTIKULSDB2" ("ARTIKUL" VARCHAR(300), "QUANTITY" INTEGER, "MED" VARCHAR(20), "VALUE" VARCHAR(20), "KONTRAGENT" VARCHAR(100), "INVOICEBYKONTRAGENT" VARCHAR(20), "DATE" VARCHAR(20), "OPERATOR" VARCHAR(20));

CREATE TABLE "APP"."BASE" ("CLIENT" VARCHAR(50), "BRAND" VARCHAR(50), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "DOING" VARCHAR(20), "READY" VARCHAR(20), "DATE" VARCHAR(20));

CREATE TABLE "APP"."SCRABTABLE4" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(40), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "SERIAL" VARCHAR(20), "BARCOD" VARCHAR(20), "SERVICEDATE" VARCHAR(20), "SCRABDATE" VARCHAR(20), "REASONS" VARCHAR(1000));

CREATE TABLE "APP"."SERVICEORDERDB" ("CLIENT" VARCHAR(50), "TYPE" VARCHAR(20), "WHEIGHT" VARCHAR(30), "BARCOD" VARCHAR(20), "SERIAL" VARCHAR(30), "CATEGORY" VARCHAR(20), "BRAND" VARCHAR(30), "T_O" VARCHAR(20), "P" VARCHAR(20), "HI" VARCHAR(20), "DOUBLE_WRITTEN" VARCHAR(20), "DATE" VARCHAR(20));

CREATE TABLE "APP"."CREDITNOTETABLE" ("ID" VARCHAR(20), "PAYMENT" VARCHAR(100), "DISCOUNT" VARCHAR(10), "INVOICESUM" VARCHAR(10), "CLIENT" VARCHAR(200), "SALLER" VARCHAR(100), "DATE" VARCHAR(20), "PROTOKOL_ID" VARCHAR(20), "ARTIKUL" VARCHAR(200), "MED" VARCHAR(20), "QUANTITY" VARCHAR(50), "PRICE" VARCHAR(20), "VALUE" VARCHAR(20), "KONTRAGENT" VARCHAR(200), "INVOICEBYKONTRAGENT" VARCHAR(20));

CREATE TABLE "APP"."MAINTABLE" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(40), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "SERIAL" VARCHAR(20), "BARCOD" VARCHAR(20), "DOING" VARCHAR(20), "DATEDOING" VARCHAR(20), "PARTS" VARCHAR(1000));

CREATE TABLE "APP"."PROTOKOLTABLEDB4" ("CLIENT" VARCHAR(100), "TYPE" VARCHAR(30), "WHEIGHT" VARCHAR(30), "BARCOD" VARCHAR(30) NOT NULL, "SERIAL" VARCHAR(30), "CATEGORY" VARCHAR(20), "BRAND" VARCHAR(50), "T_O" VARCHAR(20), "P" VARCHAR(20), "HI" VARCHAR(20), "PARTS" VARCHAR(1000), "VALUE" DOUBLE, "DOUBLE_WRITTEN" VARCHAR(10), "NUMBER" VARCHAR(20), "PERSON" VARCHAR(100), "DATE" VARCHAR(20));

CREATE TABLE "APP"."ACQUITTANCEPARENTDB" ("ID" VARCHAR(20) NOT NULL, "VALUE" VARCHAR(10), "CLIENT" VARCHAR(100), "SALLER" VARCHAR(100), "DATE" VARCHAR(20));

CREATE TABLE "APP"."INVOICEPARENTDB5" ("ID" VARCHAR(20) NOT NULL, "PAYMENT" VARCHAR(100), "DISCOUNT" VARCHAR(10), "VALUE" VARCHAR(10), "CLIENT" VARCHAR(100), "SALLER" VARCHAR(100), "DATE" VARCHAR(20), "PROTOKOL" VARCHAR(10));

CREATE TABLE "APP"."PERSONTABLE" ("NAME" VARCHAR(50), "TEL" VARCHAR(20), "DISCOUNT" VARCHAR(10));

CREATE TABLE "APP"."SERIALTABLE" ("SERIAL" VARCHAR(20));

CREATE TABLE "APP"."SERVICE" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(30), "TYPE" VARCHAR(30), "CATEGORY" VARCHAR(30), "WHEIGHT" VARCHAR(30), "SERIAL" VARCHAR(30), "BARCOD" VARCHAR(30), "SERVICEDATE" VARCHAR(30), "DOINGDATE" VARCHAR(30));

CREATE TABLE "APP"."TEAMDB" ("USSER" VARCHAR(50), "PASSWORD" VARCHAR(50), "SERVICE_ORDER" VARCHAR(20), "WORKING_BOOK" VARCHAR(20), "INVOICE" VARCHAR(20), "REPORTS" VARCHAR(20), "NEW_EXT" VARCHAR(20), "HIDDEN_MENU" VARCHAR(20), "ACQUITTANCE" VARCHAR(10), "OPERATOR_CODE" VARCHAR(20));

CREATE TABLE "APP"."SERVICETABLEDB2" ("CLIENT" VARCHAR(50), "TYPE" VARCHAR(20), "WHEIGHT" VARCHAR(30), "BARCOD" VARCHAR(20), "SERIAL" VARCHAR(30), "CATEGORY" VARCHAR(20), "BRAND" VARCHAR(30), "T_O" VARCHAR(20), "P" VARCHAR(20), "HI" VARCHAR(20), "DOUBLE_WRITTEN" VARCHAR(10), "NUMBER" VARCHAR(20), "PERSON" VARCHAR(50), "DATE" VARCHAR(20));

CREATE TABLE "APP"."HI3" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(40), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "SERIAL" VARCHAR(20), "BARCOD" VARCHAR(20), "SERVICEDATE" VARCHAR(20), "DATEDOING" VARCHAR(20), "PARTS" VARCHAR(1000), "DOING" VARCHAR(50));

CREATE TABLE "APP"."SERVICEORDERDB2" ("CLIENT" VARCHAR(50), "TYPE" VARCHAR(20), "WHEIGHT" VARCHAR(30), "BARCOD" VARCHAR(20), "SERIAL" VARCHAR(30), "CATEGORY" VARCHAR(20), "BRAND" VARCHAR(30), "T_O" VARCHAR(20), "P" VARCHAR(20), "HI" VARCHAR(20), "DOUBLE_WRITTEN" VARCHAR(20), "PERSON" VARCHAR(50), "DATE" VARCHAR(20));

CREATE TABLE "APP"."WORKTABLEDB" ("DO" VARCHAR(50), "PRICE" VARCHAR(20));

CREATE TABLE "APP"."ACQUITTANCECHILDDB_LPS" ("ID" VARCHAR(20), "ARTIKUL" VARCHAR(200), "MED" VARCHAR(20), "QUANTITY" VARCHAR(50), "PRICE" VARCHAR(20), "VALUE" VARCHAR(20), "CLIENT" VARCHAR(100));

CREATE TABLE "APP"."FIRM" ("FIRM" VARCHAR(40), "CITY" VARCHAR(20), "ADDRESS" VARCHAR(150), "EIK" VARCHAR(30), "MOL" VARCHAR(30), "PERSON" VARCHAR(60), "TEL" VARCHAR(20), "BANK" VARCHAR(40), "BIC" VARCHAR(30), "IBAN" VARCHAR(30));

CREATE TABLE "APP"."MAINTABLE_HI_2" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(40), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "SERIAL" VARCHAR(20), "BARCOD" VARCHAR(20), "DOING" VARCHAR(20), "SERVICEDATE" VARCHAR(20), "DATEDOING" VARCHAR(20), "PARTS" VARCHAR(1000));

CREATE TABLE "APP"."MAINTABLE_HI_3" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(40), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "SERIAL" VARCHAR(20), "BARCOD" VARCHAR(20), "SERVICEDATE" VARCHAR(20), "DATEDOING" VARCHAR(20), "PARTS" VARCHAR(1000));

CREATE TABLE "APP"."SERVICETABLEDB3" ("CLIENT" VARCHAR(100), "TYPE" VARCHAR(20), "WHEIGHT" VARCHAR(30), "BARCOD" VARCHAR(20), "SERIAL" VARCHAR(30), "CATEGORY" VARCHAR(20), "BRAND" VARCHAR(30), "T_O" VARCHAR(20), "P" VARCHAR(20), "HI" VARCHAR(20), "DONE" VARCHAR(20), "DOUBLE_WRITTEN" VARCHAR(20), "NUMBER" VARCHAR(20), "PERSON" VARCHAR(50), "DATE" VARCHAR(20));

CREATE TABLE "APP"."ACQUITTANCENUMBER" ("NUMBER" VARCHAR(20));

CREATE TABLE "APP"."PROTOKOLTABLEDB5" ("CLIENT" VARCHAR(100), "TYPE" VARCHAR(150), "WHEIGHT" VARCHAR(50), "BARCOD" VARCHAR(30) NOT NULL, "SERIAL" VARCHAR(30), "CATEGORY" VARCHAR(20), "BRAND" VARCHAR(50), "T_O" VARCHAR(20), "P" VARCHAR(20), "HI" VARCHAR(20), "PARTS" VARCHAR(1000), "VALUE" DOUBLE, "NUMBER" VARCHAR(20), "PERSON" VARCHAR(100), "DATE" VARCHAR(20), "UPTODATE" VARCHAR(20), "KONTRAGENT" VARCHAR(50), "INVOICEBYKONTRAGENT" VARCHAR(50), "ADDITIONAL_DATA" VARCHAR(200));

CREATE TABLE "APP"."PROFORMCHILDDB_LPS" ("ID" VARCHAR(20), "MAKE" VARCHAR(200), "MED" VARCHAR(20), "QUANTITY" VARCHAR(50), "PRICE" VARCHAR(20), "VALUE" VARCHAR(20), "CLIENT" VARCHAR(100));

CREATE TABLE "APP"."SCRABTABLE" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(40), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "SERIAL" VARCHAR(20), "BARCOD" VARCHAR(20), "DOING" VARCHAR(20), "DATEDOING" VARCHAR(20), "REASONS" VARCHAR(1000));

CREATE TABLE "APP"."PROTOKOLTABLEDB" ("CLIENT" VARCHAR(50), "TYPE" VARCHAR(20), "WHEIGHT" VARCHAR(30), "BARCOD" VARCHAR(20), "SERIAL" VARCHAR(30), "CATEGORY" VARCHAR(10), "BRAND" VARCHAR(30), "T_O" VARCHAR(20), "P" VARCHAR(20), "HI" VARCHAR(20), "PARTS" VARCHAR(1000), "PROTOKOLNUMBER" VARCHAR(20), "TEHNIK" VARCHAR(50), "DATE" VARCHAR(20));

CREATE TABLE "APP"."CREDITNOTEDB" ("ID" VARCHAR(20), "PAYMENT" VARCHAR(100), "DISCOUNT" VARCHAR(10), "INVOICESUM" VARCHAR(10), "CLIENT" VARCHAR(200), "SALLER" VARCHAR(100), "DATE" VARCHAR(20), "PROTOKOL_ID" VARCHAR(20), "ARTIKUL" VARCHAR(200), "MED" VARCHAR(20), "QUANTITY" VARCHAR(50), "PRICE" VARCHAR(20), "VALUE" VARCHAR(20), "KONTRAGENT" VARCHAR(200), "INVOICEBYKONTRAGENT" VARCHAR(20), "NOTE_ID" VARCHAR(20), "CREDIT_NOTE_DATE" VARCHAR(20));

CREATE TABLE "APP"."SERVICETABLE3" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(30), "TYPE" VARCHAR(30), "CATEGORY" VARCHAR(30), "WHEIGHT" VARCHAR(30), "SERIAL" VARCHAR(30), "BARCOD" VARCHAR(30), "DATE" VARCHAR(30));

CREATE TABLE "APP"."INVOICECHILDDB6" ("ID" VARCHAR(20), "MAKE" VARCHAR(200), "MED" VARCHAR(20), "QUANTITY" VARCHAR(50), "PRICE" VARCHAR(20), "VALUE" VARCHAR(20));

CREATE TABLE "APP"."PR_NUMBER_KAT" ("PR_NUMBER" VARCHAR(20));

CREATE TABLE "APP"."TEST2" ("ID" INTEGER, "NAME" VARCHAR(100));

CREATE TABLE "APP"."INVOICECHILDDB_LPS" ("ID" VARCHAR(20), "MAKE" VARCHAR(200), "MED" VARCHAR(20), "QUANTITY" VARCHAR(50), "PRICE" VARCHAR(20), "VALUE" VARCHAR(20), "CLIENT" VARCHAR(100));

CREATE TABLE "APP"."PROFORMNUMBER_LPS" ("PROFORM_NUMBER" VARCHAR(20));

CREATE TABLE "APP"."PROFORMPARENTDB" ("ID" VARCHAR(20) NOT NULL, "PAYMENT" VARCHAR(100), "DISCOUNT" VARCHAR(10), "VALUE" VARCHAR(10), "CLIENT" VARCHAR(100), "SALLER" VARCHAR(100), "DATE" VARCHAR(20), "PROTOKOL" VARCHAR(10));

CREATE TABLE "APP"."INVOICECHILDDB7" ("ID" VARCHAR(20), "ARTIKUL" VARCHAR(500), "MED" VARCHAR(20), "QUANTITY" VARCHAR(50), "PRICE" VARCHAR(20), "VALUE" VARCHAR(20), "CLIENT" VARCHAR(100), "KONTRAGENT" VARCHAR(50), "INVOICEBYKONTRAGENT" VARCHAR(50));

CREATE TABLE "APP"."TEST4" ("ID" INTEGER, "NAME" VARCHAR(100));

CREATE TABLE "APP"."PARTSTABLEDB_LPS" ("PART" VARCHAR(100), "TYPE" VARCHAR(20), "WHEIGHT" VARCHAR(20), "CATEGORY" VARCHAR(20), "PRICE" DOUBLE);

CREATE TABLE "APP"."NEWEXTPRICE" ("TYPE" VARCHAR(50), "WHEIGHT" VARCHAR(50), "CATEGORY" VARCHAR(20), "BRAND" VARCHAR(50), "PRICE" VARCHAR(20));

CREATE TABLE "APP"."BARCODETABLE" ("BARCOD" VARCHAR(20));

CREATE TABLE "APP"."PARTSTABLEDB" ("PART" VARCHAR(100), "TYPE" VARCHAR(20), "WHEIGHT" VARCHAR(20), "CATEGORY" VARCHAR(20), "PRICE" DOUBLE);

CREATE TABLE "APP"."NEWEXTINGUISHERSDB2" ("TYPE" VARCHAR(50), "WHEIGHT" VARCHAR(50), "CATEGORY" VARCHAR(20), "BRAND" VARCHAR(50), "QUANTITIY" INTEGER, "PRICE" VARCHAR(20));

CREATE TABLE "APP"."GREYARTIKULSDB" ("ARTIKUL" VARCHAR(100), "QUANTITY" INTEGER, "MED" VARCHAR(20), "VALUE" VARCHAR(20), "INVOICE" VARCHAR(20), "CLIENT" VARCHAR(100), "DATE" VARCHAR(20), "OPERATOR" VARCHAR(50), "PERCENTPROFIT" VARCHAR(10), "BARCODE" VARCHAR(20));

CREATE TABLE "APP"."INVOICECHILDDB4" ("ID" VARCHAR(20) NOT NULL, "MAKE" VARCHAR(200), "MED" VARCHAR(20), "QUANTITY" VARCHAR(50), "PRICE" VARCHAR(20), "VALUE" VARCHAR(20));

CREATE TABLE "APP"."ACQUITTANCE" ("ARTIKUL" VARCHAR(200), "BROI" VARCHAR(20), "MED" VARCHAR(50), "VALUE" VARCHAR(20), "NUMBER" VARCHAR(20) NOT NULL, "SALLER" VARCHAR(50), "CLIENT" VARCHAR(50), "DATE" VARCHAR(20));

CREATE TABLE "APP"."PRICETABLEDB" ("PART" VARCHAR(50), "TYPE" VARCHAR(20), "WHEIGHT" VARCHAR(20), "CATEGORY" VARCHAR(20), "PRICE" VARCHAR(20));

CREATE TABLE "APP"."SERVICETABLEDB" ("CLIENT" VARCHAR(100), "TYPE" VARCHAR(20), "WHEIGHT" VARCHAR(30), "BARCOD" VARCHAR(20) NOT NULL, "SERIAL" VARCHAR(30), "CATEGORY" VARCHAR(20), "BRAND" VARCHAR(30), "T_O" VARCHAR(20), "P" VARCHAR(20), "HI" VARCHAR(20), "DONE" VARCHAR(20), "NUMBER" VARCHAR(20), "PERSON" VARCHAR(50), "DATE" VARCHAR(20), "ADDITIONAL_DATA" VARCHAR(200));

CREATE TABLE "APP"."INVOICEPARENTDB3" ("ID" VARCHAR(20), "PAYMENT" VARCHAR(20), "DISCOUNT" VARCHAR(10), "VALUE" VARCHAR(10), "CLIENT" VARCHAR(100), "SALLER" VARCHAR(100), "DATE" VARCHAR(20));

CREATE TABLE "APP"."SERVICETABLE" ("CLIENT" VARCHAR(30), "BRAND" VARCHAR(30), "TYPE" VARCHAR(30), "CATEGORY" VARCHAR(30), "WHEIGHT" VARCHAR(30), "SERIAL" VARCHAR(30), "BARCOD" VARCHAR(30), "DATE" VARCHAR(30));

CREATE TABLE "APP"."FIRMSTABLE" ("FIRM" VARCHAR(100) NOT NULL, "CITY" VARCHAR(50), "ADDRESS" VARCHAR(100), "EIK" VARCHAR(50), "MOL" VARCHAR(50), "EMAIL" VARCHAR(30), "PERSON" VARCHAR(50), "TELPERSON" VARCHAR(30), "BANK" VARCHAR(30), "BIC" VARCHAR(30), "IBAN" VARCHAR(30), "DISCOUNT" VARCHAR(10), "INCORRECTPERSON" VARCHAR(2), "VAT_REGISTRATION" VARCHAR(10));

CREATE TABLE "APP"."BARCODES" ("BARCOD" VARCHAR(15));

CREATE TABLE "APP"."SCRABTABLE3" ("CLIENT" VARCHAR(40), "BRAND" VARCHAR(40), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "SERIAL" VARCHAR(20), "BARCOD" VARCHAR(20), "DATE" VARCHAR(20), "REASONS" VARCHAR(1000));

CREATE TABLE "APP"."TEST7" ("ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(255));

CREATE TABLE "APP"."BRACKTABLEDB2" ("CLIENT" VARCHAR(50), "TYPE" VARCHAR(50), "WHEIGHT" VARCHAR(50), "BARCOD" VARCHAR(20) NOT NULL, "SERIAL" VARCHAR(30), "CATEGORY" VARCHAR(20), "BRAND" VARCHAR(50), "REASONS" VARCHAR(200), "NUMBER" VARCHAR(20), "TEHNIK" VARCHAR(50), "DATE" VARCHAR(20));

CREATE TABLE "APP"."NEWEXTINGUISHERSDB3" ("TYPE" VARCHAR(150), "WHEIGHT" VARCHAR(50), "CATEGORY" VARCHAR(20), "BRAND" VARCHAR(50), "QUANTITIY" INTEGER, "PRICE" VARCHAR(20), "INVOICE" VARCHAR(50), "CLIENT" VARCHAR(50), "DATE" VARCHAR(50), "OPERATOR" VARCHAR(50), "PERCENTPROFIT" VARCHAR(50));

CREATE TABLE "APP"."TEST3" ("ID" INTEGER, "NAME" VARCHAR(100));

CREATE TABLE "APP"."PERSON" ("NAME" VARCHAR(50), "TEL" VARCHAR(20));

CREATE TABLE "APP"."PROFORMNUMBER" ("PROFORM_NUMBER" VARCHAR(20));

CREATE TABLE "APP"."INVOICEPARENTDB_LPS" ("ID" VARCHAR(20) NOT NULL, "PAYMENT" VARCHAR(100), "DISCOUNT" VARCHAR(10), "VALUE" VARCHAR(10), "CLIENT" VARCHAR(100), "SALLER" VARCHAR(100), "DATE" VARCHAR(20), "PROTOKOL" VARCHAR(10));

CREATE TABLE "APP"."PROFORMPARENTDB_LPS" ("ID" VARCHAR(20) NOT NULL, "PAYMENT" VARCHAR(100), "DISCOUNT" VARCHAR(10), "VALUE" VARCHAR(10), "CLIENT" VARCHAR(100), "SALLER" VARCHAR(100), "DATE" VARCHAR(20), "PROTOKOL" VARCHAR(10));

CREATE TABLE "APP"."ACQUITTANCEPARENTDB_LPS" ("ID" VARCHAR(20) NOT NULL, "VALUE" VARCHAR(10), "CLIENT" VARCHAR(100), "SALLER" VARCHAR(100), "DATE" VARCHAR(20));

CREATE TABLE "APP"."MAIN" ("CLIENT" VARCHAR(50), "BRAND" VARCHAR(50), "TYPE" VARCHAR(20), "CATEGORY" VARCHAR(20), "WHEIGHT" VARCHAR(20), "DOING" VARCHAR(20), "READY" VARCHAR(20));

CREATE TABLE "APP"."INVOICEPARENTDB" ("ID" VARCHAR(20) NOT NULL, "PAYMENT" VARCHAR(20), "DISCOUNT" VARCHAR(10), "VALUE" VARCHAR(10), "CLIENT" VARCHAR(20), "SALLER" VARCHAR(20), "DATE" VARCHAR(20));

-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- primary/unique
ALTER TABLE "APP"."PERSONSTABLE" ADD CONSTRAINT "SQL150917112243470" PRIMARY KEY ("NAME");

ALTER TABLE "APP"."PROFORMPARENTDB" ADD CONSTRAINT "SQL150806104421970" PRIMARY KEY ("ID");

ALTER TABLE "APP"."INVOICECHILDDB2" ADD CONSTRAINT "SQL150802172348010" PRIMARY KEY ("ID");

ALTER TABLE "APP"."INVOICEPARENTDB4" ADD CONSTRAINT "SQL150802203759960" PRIMARY KEY ("ID");

ALTER TABLE "APP"."INVOICECHILDDB" ADD CONSTRAINT "SQL150802172137320" PRIMARY KEY ("ID");

ALTER TABLE "APP"."ACQUITTANCEPARENTDB" ADD CONSTRAINT "SQL151008112613710" PRIMARY KEY ("ID");

ALTER TABLE "APP"."INVOICECHILDDB3" ADD CONSTRAINT "SQL150802180152160" PRIMARY KEY ("ID");

ALTER TABLE "APP"."PROFORMPARENTDB_LPS" ADD CONSTRAINT "SQL200806103314330" PRIMARY KEY ("ID");

ALTER TABLE "APP"."ACQUITTANCEPARENTDB_LPS" ADD CONSTRAINT "SQL200806103513690" PRIMARY KEY ("ID");

ALTER TABLE "APP"."BRACKTABLEDB2" ADD CONSTRAINT "SQL150807152121280" PRIMARY KEY ("BARCOD");

ALTER TABLE "APP"."COMPOSITE" ADD CONSTRAINT "SQL150829205716030" PRIMARY KEY ("INVOICE", "PROTOKOL");

ALTER TABLE "APP"."INVOICEPARENTDB2" ADD CONSTRAINT "SQL150802171206460" PRIMARY KEY ("ID");

ALTER TABLE "APP"."FRIENDS" ADD CONSTRAINT "SQL150820161927210" PRIMARY KEY ("ID");

ALTER TABLE "APP"."INVOICEPARENTDB5" ADD CONSTRAINT "SQL150804105554620" PRIMARY KEY ("ID");

ALTER TABLE "APP"."TEST7" ADD CONSTRAINT "SQL240327202740620" PRIMARY KEY ("ID");

ALTER TABLE "APP"."PROTOKOLTABLEDB5" ADD CONSTRAINT "SQL160518104531640" PRIMARY KEY ("BARCOD");

ALTER TABLE "APP"."INVOICECHILDDB4" ADD CONSTRAINT "SQL150802203442170" PRIMARY KEY ("ID");

ALTER TABLE "APP"."SERVICETABLEDB" ADD CONSTRAINT "SQL150807144122120" PRIMARY KEY ("BARCOD");

ALTER TABLE "APP"."FIRMSTABLE" ADD CONSTRAINT "SQL150917112925310" PRIMARY KEY ("FIRM");

ALTER TABLE "APP"."INVOICEPARENTDB" ADD CONSTRAINT "SQL150802170401200" PRIMARY KEY ("ID");

ALTER TABLE "APP"."PROTOKOLTABLEDB4" ADD CONSTRAINT "SQL150807144947650" PRIMARY KEY ("BARCOD");

ALTER TABLE "APP"."ACQUITTANCE" ADD CONSTRAINT "SQL151006170044830" PRIMARY KEY ("NUMBER");

ALTER TABLE "APP"."INVOICEPARENTDB_LPS" ADD CONSTRAINT "SQL200806101555890" PRIMARY KEY ("ID");

-- foreign
ALTER TABLE "APP"."ACQUITTANCECHILDDB" ADD CONSTRAINT "SQL151008120245250" FOREIGN KEY ("ID") REFERENCES "APP"."ACQUITTANCEPARENTDB" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."PROFORMCHILDDB_LPS" ADD CONSTRAINT "SQL200806103349520" FOREIGN KEY ("ID") REFERENCES "APP"."PROFORMPARENTDB_LPS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."PROFORMCHILDDB" ADD CONSTRAINT "SQL150806110558500" FOREIGN KEY ("ID") REFERENCES "APP"."PROFORMPARENTDB" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."PROFORMCHILDDB2" ADD CONSTRAINT "SQL150811151326510" FOREIGN KEY ("ID") REFERENCES "APP"."PROFORMPARENTDB" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."INVOICECHILDDB6" ADD CONSTRAINT "SQL150804115013440" FOREIGN KEY ("ID") REFERENCES "APP"."INVOICEPARENTDB5" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."INVOICECHILDDB_LPS" ADD CONSTRAINT "SQL200806101607740" FOREIGN KEY ("ID") REFERENCES "APP"."INVOICEPARENTDB_LPS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."INVOICEPARENTDB3" ADD CONSTRAINT "SQL150802180156640" FOREIGN KEY ("ID") REFERENCES "APP"."INVOICECHILDDB3" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."INVOICECHILDDB7" ADD CONSTRAINT "SQL150811140812220" FOREIGN KEY ("ID") REFERENCES "APP"."INVOICEPARENTDB5" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."INVOICECHILDDB4" ADD CONSTRAINT "SQL150802203442171" FOREIGN KEY ("ID") REFERENCES "APP"."INVOICECHILDDB4" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."ACQUITTANCECHILDDB_LPS" ADD CONSTRAINT "SQL200806103550500" FOREIGN KEY ("ID") REFERENCES "APP"."ACQUITTANCEPARENTDB_LPS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."INVOICECHILDDB5" ADD CONSTRAINT "SQL150802204429440" FOREIGN KEY ("ID") REFERENCES "APP"."INVOICEPARENTDB4" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

